"""
╔══════════════════════════════════════════════════════════════════╗
║          NDA4 AI AGENT SOLANA TRADING BOT v2.0                  ║
║     Auto Trade | Auto Learn | Auto Improve | Paper Trading       ║
╚══════════════════════════════════════════════════════════════════╝

Gabungan dari:
- NDA4 AI Agent Trading Bot (scan + AI entry + Telegram)
- Memecoin Scanner Skill (paper trading + self-improving + journal)

Features:
- Real-time on-chain scanning (DexScreener + GMGN + Birdeye + pump.fun)
- AI Agent via OpenRouter: putuskan entry type, TP, SL, confidence score
- Entry Scoring System (0-100) mirip Memecoin Skill — butuh 70+ untuk BUY
- Paper trading mode (aman, bisa diaktifkan via PAPER_TRADE=true)
- Auto-improve filters setelah 3x loss berturut-turut
- Telegram: notif per trade + laporan tiap 1 jam
- Win Rate tracking + pattern library yang berkembang otomatis
- Trading Journal (.md) yang di-update setelah setiap trade
- Risk management rules yang ketat
"""

import asyncio
import aiohttp
import json
import logging
import os
import time
import copy
from datetime import datetime, timedelta
from typing import Optional
from dataclasses import dataclass, field
from collections import deque
from pathlib import Path

# ──────────────────────────────────────────────────────────────────
# CONFIG
# ──────────────────────────────────────────────────────────────────
TELEGRAM_BOT_TOKEN   = os.getenv("TELEGRAM_BOT_TOKEN", "YOUR_BOT_TOKEN")
TELEGRAM_CHAT_ID     = os.getenv("TELEGRAM_CHAT_ID", "YOUR_CHAT_ID")
OPENROUTER_API_KEY   = os.getenv("OPENROUTER_API_KEY", "YOUR_OPENROUTER_KEY")
OPENROUTER_MODEL     = os.getenv("OPENROUTER_MODEL", "openrouter/owl-alpha")
OPENROUTER_BASE_URL  = "https://openrouter.ai/api/v1/chat/completions"

# Mode: set PAPER_TRADE=false untuk live (hati-hati!)
PAPER_TRADE          = os.getenv("PAPER_TRADE", "true").lower() != "false"

# Trading parameters
INITIAL_BALANCE_SOL       = float(os.getenv("INITIAL_BALANCE", "1.0"))
TRADE_SIZE_SOL            = float(os.getenv("TRADE_SIZE", "0.03"))
MAX_OPEN_TRADES           = int(os.getenv("MAX_OPEN_TRADES", "5"))
SCAN_INTERVAL_SEC         = int(os.getenv("SCAN_INTERVAL", "60"))
REPORT_INTERVAL_SEC       = 3600
TARGET_WIN_RATE           = 0.55
CONSECUTIVE_LOSS_TRIGGER  = 3
MIN_ENTRY_SCORE           = 70       # Minimum score 0-100 untuk BUY
MAX_DAILY_LOSS_PCT        = 0.20     # Stop trading jika portfolio turun 20% sehari
MAX_CONSECUTIVE_LOSSES    = 5        # Pause jika 5x loss berturut-turut
STOP_LOSS_PCT             = 0.30     # Default hard SL -30%
CHASE_LIMIT_MULTIPLIER    = 3.0      # Jangan chase token yang sudah 3x

# Paths untuk journal & strategi
REFERENCES_DIR   = Path("references")
JOURNAL_FILE     = REFERENCES_DIR / "trading_journal.md"
STRATEGY_FILE    = REFERENCES_DIR / "strategy_evolution.md"
WATCHLIST_FILE   = REFERENCES_DIR / "wallet_watchlist.md"
BLACKLIST_FILE   = REFERENCES_DIR / "token_blacklist.md"

# ──────────────────────────────────────────────────────────────────
# REFERENCE FILE MANAGER
# ──────────────────────────────────────────────────────────────────

def init_reference_files():
    """Buat folder & file referensi jika belum ada"""
    REFERENCES_DIR.mkdir(exist_ok=True)

    if not JOURNAL_FILE.exists():
        JOURNAL_FILE.write_text("# Trading Journal\n\n_Auto-generated by NDA4 Bot v2_\n\n")

    if not STRATEGY_FILE.exists():
        STRATEGY_FILE.write_text(
            "# Strategy Evolution\n\n_Auto-generated by NDA4 Bot v2_\n\n"
            "## Initial Strategy — Generation 1\n"
            "- Min liquidity: $15k\n- Min volume 24h: $10k\n- Min holders: 100\n"
            "- Buy/sell ratio: 1.5x\n- TP: +25% | SL: -8%\n\n"
        )

    if not WATCHLIST_FILE.exists():
        WATCHLIST_FILE.write_text("# Smart Money Wallet Watchlist\n\n_Add wallets to track here_\n\n")

    if not BLACKLIST_FILE.exists():
        BLACKLIST_FILE.write_text("# Token Blacklist\n\n_Tokens/patterns to avoid_\n\n")


def append_to_journal(text: str):
    try:
        with open(JOURNAL_FILE, "a", encoding="utf-8") as f:
            f.write(text + "\n")
    except Exception as e:
        logging.warning(f"Journal write error: {e}")


def append_to_strategy(text: str):
    try:
        with open(STRATEGY_FILE, "a", encoding="utf-8") as f:
            f.write(text + "\n")
    except Exception as e:
        logging.warning(f"Strategy write error: {e}")


# ──────────────────────────────────────────────────────────────────
# DATA STRUCTURES
# ──────────────────────────────────────────────────────────────────

@dataclass
class FilterConfig:
    """AI-tunable filter parameters — auto-improved saat sering loss"""
    min_liquidity_usd: float   = 15_000
    min_volume_24h_usd: float  = 10_000
    min_holder_count: int      = 100
    max_price_impact_pct: float = 3.0
    min_price_change_5m: float = 2.0
    max_price_change_5m: float = 25.0
    min_tx_count_5m: int       = 20
    min_buy_sell_ratio: float  = 1.5
    min_market_cap_usd: float  = 30_000
    max_market_cap_usd: float  = 5_000_000
    require_renounced: bool    = False
    require_burned_lp: bool    = False
    bundle_threshold: float    = 0.25
    min_age_minutes: int       = 5
    max_age_hours: int         = 24
    tp_multiplier: float       = 1.25
    sl_multiplier: float       = 0.92
    generation: int            = 1

    def to_prompt(self) -> str:
        return f"""
CURRENT FILTER CONFIG (Generation {self.generation}):
- Minimum Liquidity: ${self.min_liquidity_usd:,.0f}
- Minimum 24h Volume: ${self.min_volume_24h_usd:,.0f}
- Minimum Holders: {self.min_holder_count}
- Max Price Impact: {self.max_price_impact_pct}%
- Price Change 5m Range: {self.min_price_change_5m}% - {self.max_price_change_5m}%
- Min Tx 5m: {self.min_tx_count_5m}
- Min Buy/Sell Ratio: {self.min_buy_sell_ratio}x
- Market Cap Range: ${self.min_market_cap_usd:,.0f} - ${self.max_market_cap_usd:,.0f}
- Max Bundle %: {self.bundle_threshold*100:.0f}%
- Token Age: {self.min_age_minutes}m - {self.max_age_hours}h
- TP: +{(self.tp_multiplier-1)*100:.0f}% | SL: -{(1-self.sl_multiplier)*100:.0f}%
"""


@dataclass
class TokenData:
    """Raw data dari scanner"""
    address: str
    symbol: str
    name: str
    price_usd: float
    price_sol: float
    liquidity_usd: float
    volume_24h: float
    volume_5m: float
    price_change_5m: float
    price_change_1h: float
    price_change_24h: float
    market_cap: float
    holder_count: int
    tx_count_5m: int
    buy_count_5m: int
    sell_count_5m: int
    age_minutes: float
    dex: str
    pair_address: str
    scanned_at: float = field(default_factory=time.time)

    def entry_score(self) -> int:
        """
        Hitung entry score 0-100 berdasarkan kriteria Memecoin Skill.
        Butuh 70+ untuk BUY.
        """
        score = 0

        # Liquidity (0-20)
        if self.liquidity_usd >= 50_000:
            score += 20
        elif self.liquidity_usd >= 30_000:
            score += 14
        elif self.liquidity_usd >= 10_000:
            score += 8

        # Holder distribution proxy — pakai holder_count (0-20)
        if self.holder_count >= 500:
            score += 20
        elif self.holder_count >= 200:
            score += 14
        elif self.holder_count >= 100:
            score += 8

        # Momentum / buy pressure (0-15)
        if 5 <= self.price_change_5m <= 15:
            score += 15
        elif 2 <= self.price_change_5m <= 25:
            score += 8

        # Buy/sell ratio (0-15)
        ratio = self.buy_count_5m / self.sell_count_5m if self.sell_count_5m > 0 else self.buy_count_5m
        if ratio >= 3.0:
            score += 15
        elif ratio >= 2.0:
            score += 10
        elif ratio >= 1.5:
            score += 6

        # Volume 24h (0-15)
        if self.volume_24h >= 100_000:
            score += 15
        elif self.volume_24h >= 50_000:
            score += 10
        elif self.volume_24h >= 10_000:
            score += 6

        # Token age — tidak terlalu baru, tidak terlalu lama (0-15)
        if 15 <= self.age_minutes <= 360:
            score += 15
        elif 5 <= self.age_minutes <= 1440:
            score += 8

        return min(score, 100)


@dataclass
class Trade:
    """Satu posisi trading"""
    id: str
    token_address: str
    token_symbol: str
    entry_type: str
    entry_price: float
    entry_price_sol: float
    tp_price: float
    sl_price: float
    size_sol: float
    status: str
    opened_at: float
    entry_score: int = 0
    closed_at: Optional[float] = None
    exit_price: Optional[float] = None
    pnl_sol: Optional[float] = None
    pnl_pct: Optional[float] = None
    ai_reasoning: str = ""
    current_price: float = 0.0
    last_updated: float = field(default_factory=time.time)
    is_paper: bool = True

    @property
    def is_active(self):
        return self.status in ("open", "pending_limit")

    @property
    def pnl_display(self):
        if self.pnl_sol is None:
            if self.status == "open" and self.current_price:
                pnl = (self.current_price - self.entry_price) / self.entry_price * self.size_sol
                return f"{pnl:+.4f} SOL ({(self.current_price/self.entry_price-1)*100:+.1f}%)"
            return "—"
        return f"{self.pnl_sol:+.4f} SOL ({self.pnl_pct:+.1f}%)"

    @property
    def duration_str(self) -> str:
        end = self.closed_at or time.time()
        mins = int((end - self.opened_at) / 60)
        if mins < 60:
            return f"{mins}m"
        return f"{mins//60}h {mins%60}m"


@dataclass
class BotState:
    """State lengkap bot"""
    balance_sol: float             = INITIAL_BALANCE_SOL
    initial_balance_sol: float     = INITIAL_BALANCE_SOL
    trades: list                   = field(default_factory=list)
    filters: FilterConfig          = field(default_factory=FilterConfig)
    consecutive_losses: int        = 0
    total_trades: int              = 0
    winning_trades: int            = 0
    losing_trades: int             = 0
    total_pnl_sol: float           = 0.0
    improve_count: int             = 0
    started_at: float              = field(default_factory=time.time)
    last_report_at: float          = field(default_factory=time.time)
    scanned_tokens_today: int      = 0
    skipped_tokens_today: int      = 0
    daily_loss_triggered: bool     = False
    paused_due_to_losses: bool     = False
    recent_losses: deque           = field(default_factory=lambda: deque(maxlen=10))
    trade_counter: int             = 0

    @property
    def win_rate(self) -> float:
        finished = self.winning_trades + self.losing_trades
        return self.winning_trades / finished if finished > 0 else 0.0

    @property
    def open_trades(self):
        return [t for t in self.trades if t.is_active]

    @property
    def finished_trades(self):
        return [t for t in self.trades if not t.is_active]

    @property
    def portfolio_change_pct(self) -> float:
        if self.initial_balance_sol == 0:
            return 0.0
        return (self.balance_sol - self.initial_balance_sol) / self.initial_balance_sol

    def can_open_trade(self) -> bool:
        if self.daily_loss_triggered:
            return False
        if self.paused_due_to_losses:
            return False
        if len(self.open_trades) >= MAX_OPEN_TRADES:
            return False
        if self.balance_sol < TRADE_SIZE_SOL:
            return False
        return True

    def check_daily_loss_limit(self) -> bool:
        """Return True jika daily loss limit terpicu"""
        if self.portfolio_change_pct <= -MAX_DAILY_LOSS_PCT:
            self.daily_loss_triggered = True
            return True
        return False

    def new_trade_id(self) -> str:
        self.trade_counter += 1
        return f"T{self.trade_counter:04d}"


# ──────────────────────────────────────────────────────────────────
# SCANNER — DexScreener + GMGN (fallback ke DexScreener)
# ──────────────────────────────────────────────────────────────────

class SolanaScanner:
    DEXSCREENER_BASE = "https://api.dexscreener.com/latest/dex"

    async def get_trending_tokens(self, session: aiohttp.ClientSession) -> list[TokenData]:
        tokens = []
        try:
            url = f"{self.DEXSCREENER_BASE}/search?q=SOL"
            async with session.get(url, timeout=aiohttp.ClientTimeout(total=12)) as r:
                if r.status != 200:
                    return tokens
                data = await r.json()
                pairs = data.get("pairs", [])
            sol_pairs = [p for p in pairs if p.get("chainId") == "solana"]
            for p in sol_pairs[:60]:
                token = self._parse_pair(p)
                if token:
                    tokens.append(token)
        except Exception as e:
            logging.warning(f"Trending scanner error: {e}")
        return tokens

    async def get_new_tokens(self, session: aiohttp.ClientSession) -> list[TokenData]:
        tokens = []
        try:
            url = f"{self.DEXSCREENER_BASE}/tokens/solana"
            async with session.get(url, timeout=aiohttp.ClientTimeout(total=12)) as r:
                if r.status != 200:
                    return tokens
                data = await r.json()
                pairs = data.get("pairs", [])
            for p in pairs[:40]:
                token = self._parse_pair(p)
                if token:
                    tokens.append(token)
        except Exception as e:
            logging.warning(f"New token scanner error: {e}")
        return tokens

    async def get_token_detail(self, session: aiohttp.ClientSession, address: str) -> Optional[TokenData]:
        try:
            url = f"{self.DEXSCREENER_BASE}/tokens/{address}"
            async with session.get(url, timeout=aiohttp.ClientTimeout(total=8)) as r:
                if r.status != 200:
                    return None
                data = await r.json()
                pairs = data.get("pairs", [])
                if not pairs:
                    return None
                best = max(pairs, key=lambda x: float(x.get("liquidity", {}).get("usd", 0) or 0))
                return self._parse_pair(best)
        except Exception:
            return None

    def _parse_pair(self, p: dict) -> Optional[TokenData]:
        try:
            base        = p.get("baseToken", {})
            price_usd   = float(p.get("priceUsd", 0) or 0)
            price_native = float(p.get("priceNative", 0) or 0)
            liq         = p.get("liquidity", {})
            vol         = p.get("volume", {})
            pc          = p.get("priceChange", {})
            txns_5m     = p.get("txns", {}).get("m5", {})
            info        = p.get("info", {})
            created_at  = p.get("pairCreatedAt", 0)
            age_minutes = (time.time() * 1000 - (created_at or time.time() * 1000)) / 60000

            holders = 0
            for ext in (info.get("extensions") or []):
                if isinstance(ext, dict) and ext.get("type") == "holders":
                    holders = int(ext.get("value", 0))

            buy5  = int(txns_5m.get("buys", 0) or 0)
            sell5 = int(txns_5m.get("sells", 0) or 0)

            if price_usd <= 0:
                return None

            return TokenData(
                address=base.get("address", ""),
                symbol=base.get("symbol", "???"),
                name=base.get("name", "Unknown"),
                price_usd=price_usd,
                price_sol=price_native,
                liquidity_usd=float(liq.get("usd", 0) or 0),
                volume_24h=float(vol.get("h24", 0) or 0),
                volume_5m=float(vol.get("m5", 0) or 0),
                price_change_5m=float(pc.get("m5", 0) or 0),
                price_change_1h=float(pc.get("h1", 0) or 0),
                price_change_24h=float(pc.get("h24", 0) or 0),
                market_cap=float(p.get("marketCap", 0) or 0),
                holder_count=holders,
                tx_count_5m=buy5 + sell5,
                buy_count_5m=buy5,
                sell_count_5m=sell5,
                age_minutes=max(0, age_minutes),
                dex=p.get("dexId", "unknown"),
                pair_address=p.get("pairAddress", ""),
            )
        except Exception:
            return None


# ──────────────────────────────────────────────────────────────────
# FILTER ENGINE — Hard filters sebelum AI
# ──────────────────────────────────────────────────────────────────

class FilterEngine:
    def passes(self, token: TokenData, cfg: FilterConfig) -> tuple[bool, str]:
        if token.liquidity_usd < cfg.min_liquidity_usd:
            return False, f"Liquidity ${token.liquidity_usd:,.0f} < ${cfg.min_liquidity_usd:,.0f}"
        if token.volume_24h < cfg.min_volume_24h_usd:
            return False, f"Volume24h ${token.volume_24h:,.0f} < ${cfg.min_volume_24h_usd:,.0f}"
        if token.price_change_5m < cfg.min_price_change_5m:
            return False, f"Momentum 5m {token.price_change_5m:+.1f}% terlalu lemah"
        if token.price_change_5m > cfg.max_price_change_5m:
            return False, f"Pump 5m {token.price_change_5m:+.1f}% terlalu tinggi (risiko dump)"
        if token.tx_count_5m < cfg.min_tx_count_5m:
            return False, f"Tx 5m {token.tx_count_5m} < {cfg.min_tx_count_5m}"
        if 0 < token.market_cap < cfg.min_market_cap_usd:
            return False, f"MCap ${token.market_cap:,.0f} terlalu kecil"
        if token.market_cap > cfg.max_market_cap_usd:
            return False, f"MCap ${token.market_cap:,.0f} terlalu besar"
        if token.age_minutes < cfg.min_age_minutes:
            return False, f"Token terlalu baru ({token.age_minutes:.0f}m)"
        if token.age_minutes > cfg.max_age_hours * 60:
            return False, f"Token terlalu lama ({token.age_minutes/60:.1f}h)"
        if token.sell_count_5m > 0:
            ratio = token.buy_count_5m / token.sell_count_5m
            if ratio < cfg.min_buy_sell_ratio:
                return False, f"Buy/Sell ratio {ratio:.1f}x < {cfg.min_buy_sell_ratio}x"
        if token.holder_count > 0 and token.holder_count < cfg.min_holder_count:
            return False, f"Holders {token.holder_count} < {cfg.min_holder_count}"
        return True, ""


# ──────────────────────────────────────────────────────────────────
# AI AGENT — OpenRouter decides entry, TP, SL, improves filters
# ──────────────────────────────────────────────────────────────────

class AIAgent:
    def __init__(self):
        self.headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {OPENROUTER_API_KEY}",
            "HTTP-Referer": "https://github.com/aldiboncel49-lgtm/tes/",
            "X-Title": "NDA4 Solana Trading Bot v2",
        }

    async def _call_api(self, session: aiohttp.ClientSession, prompt: str, max_tokens: int = 500) -> Optional[str]:
        payload = {
            "model": OPENROUTER_MODEL,
            "max_tokens": max_tokens,
            "messages": [{"role": "user", "content": prompt}]
        }
        try:
            async with session.post(
                OPENROUTER_BASE_URL,
                headers=self.headers,
                json=payload,
                timeout=aiohttp.ClientTimeout(total=30)
            ) as r:
                if r.status != 200:
                    err = await r.text()
                    logging.error(f"OpenRouter error {r.status}: {err[:200]}")
                    return None
                data = await r.json()
                return data["choices"][0]["message"]["content"].strip()
        except Exception as e:
            logging.error(f"OpenRouter call error: {e}")
            return None

    async def analyze_token(
        self, session: aiohttp.ClientSession, token: TokenData, state: BotState
    ) -> Optional[dict]:
        score = token.entry_score()
        prompt = f"""
Kamu adalah AI trading agent Solana on-chain yang konservatif dan disiplin.

{state.filters.to_prompt()}

TOKEN DATA (REAL-TIME):
- Symbol: {token.symbol} ({token.name})
- Address: {token.address}
- Price: ${token.price_usd:.8f} ({token.price_sol:.8f} SOL)
- Liquidity: ${token.liquidity_usd:,.0f}
- Volume 24h: ${token.volume_24h:,.0f}
- Volume 5m: ${token.volume_5m:,.0f}
- Price Change 5m/1h/24h: {token.price_change_5m:+.1f}% / {token.price_change_1h:+.1f}% / {token.price_change_24h:+.1f}%
- Market Cap: ${token.market_cap:,.0f}
- Holders: {token.holder_count}
- Tx 5m: {token.tx_count_5m} (Buy: {token.buy_count_5m} | Sell: {token.sell_count_5m})
- Age: {token.age_minutes:.0f} menit
- DEX: {token.dex}
- Entry Score (pre-calc): {score}/100

BOT STATE:
- Balance: {state.balance_sol:.3f} SOL
- Trade size: {TRADE_SIZE_SOL} SOL
- Open trades: {len(state.open_trades)}/{MAX_OPEN_TRADES}
- Current Win Rate: {state.win_rate*100:.1f}%
- Consecutive losses: {state.consecutive_losses}
- Total trades: {state.total_trades}
- Mode: {"PAPER TRADING" if PAPER_TRADE else "LIVE"}

RISK RULES (WAJIB DIPATUHI):
- Jangan BUY jika token sudah naik 3x dari harga awal
- Jangan BUY jika ada 5+ consecutive losses (paused)
- Minimum entry score: {MIN_ENTRY_SCORE}/100
- TP minimal 15% di atas entry, SL maksimal -30% dari entry

INSTRUKSI:
1. Evaluasi semua data di atas
2. Putuskan: BUY atau SKIP
3. Jika BUY: tentukan entry_type (market/limit), entry_price, tp_price, sl_price
   - limit: entry 1-2% di bawah harga sekarang
   - market: entry di harga sekarang
4. Berikan confidence score 0-100 (hanya BUY jika confidence >= 60)

Jawab HANYA dengan JSON ini (tanpa backtick, tanpa teks lain):
{{
  "action": "BUY" or "SKIP",
  "entry_type": "market" or "limit",
  "entry_price_usd": float,
  "tp_price_usd": float,
  "sl_price_usd": float,
  "confidence": 0-100,
  "reasoning": "singkat max 2 kalimat",
  "skip_reason": "jika SKIP, alasan singkat"
}}
"""
        text = await self._call_api(session, prompt, max_tokens=400)
        if not text:
            return None
        try:
            text = text.replace("```json", "").replace("```", "").strip()
            return json.loads(text)
        except Exception as e:
            logging.error(f"AI analyze parse error: {e} | raw: {text[:200]}")
            return None

    async def improve_filters(
        self, session: aiohttp.ClientSession, state: BotState
    ) -> tuple:
        recent_losses_text = "\n".join([
            f"- {t.token_symbol}: Entry ${t.entry_price:.6f}, Exit ${t.exit_price:.6f}, "
            f"PnL {t.pnl_pct:+.1f}%, Score {t.entry_score}/100, Duration {t.duration_str}"
            for t in list(state.recent_losses)[-5:]
            if t.pnl_sol is not None
        ]) or "Tidak ada detail loss tersedia"

        current = state.filters
        prompt = f"""
Kamu adalah AI filter optimizer untuk trading bot Solana on-chain.

Bot mengalami {state.consecutive_losses} loss berturut-turut.
Current win rate: {state.win_rate*100:.1f}% (target: 55%).
Filter generation saat ini: #{current.generation}.

RECENT LOSSES:
{recent_losses_text}

FILTER SAAT INI:
{current.to_prompt()}

ANALISIS & TUGAS:
Cari pola di loss tersebut (entry score terlalu rendah? age terlalu baru?
buy/sell ratio lemah? market cap terlalu besar/kecil?), lalu sesuaikan filter
untuk meningkatkan win rate ke 55%+.

Strategi yang bisa dilakukan:
- Naikkan min_liquidity, min_volume_24h
- Perketat min_buy_sell_ratio
- Sesuaikan rentang price_change_5m
- Sesuaikan TP/SL (tp_multiplier / sl_multiplier)
- Naikkan min_age_minutes (hindari token terlalu baru)
- Naikkan min_holder_count

Jawab HANYA dengan JSON (tanpa backtick):
{{
  "min_liquidity_usd": float,
  "min_volume_24h_usd": float,
  "min_holder_count": int,
  "max_price_impact_pct": float,
  "min_price_change_5m": float,
  "max_price_change_5m": float,
  "min_tx_count_5m": int,
  "min_buy_sell_ratio": float,
  "min_market_cap_usd": float,
  "max_market_cap_usd": float,
  "bundle_threshold": float,
  "min_age_minutes": int,
  "max_age_hours": int,
  "tp_multiplier": float,
  "sl_multiplier": float,
  "improvement_notes": "apa yang diubah dan kenapa (max 3 kalimat)"
}}
"""
        text = await self._call_api(session, prompt, max_tokens=600)
        if not text:
            return self._fallback_improve(current)
        try:
            text = text.replace("```json", "").replace("```", "").strip()
            data = json.loads(text)
            notes = data.pop("improvement_notes", "Auto-improved")
            new_filters = FilterConfig(**data, generation=current.generation + 1)
            return new_filters, notes
        except Exception as e:
            logging.error(f"AI improve parse error: {e}")
            return self._fallback_improve(current)

    async def generate_pattern_update(
        self, session: aiohttp.ClientSession, state: BotState
    ) -> Optional[str]:
        """Setiap 10 trade, AI update pattern library"""
        finished = state.finished_trades[-10:]
        if len(finished) < 5:
            return None

        wins = [t for t in finished if t.pnl_sol and t.pnl_sol > 0]
        losses = [t for t in finished if t.pnl_sol and t.pnl_sol <= 0]

        prompt = f"""
Analisis 10 trade terakhir bot Solana ini dan temukan pola BULLISH dan BEARISH.

WINS ({len(wins)}):
{chr(10).join([f"- {t.token_symbol}: Score {t.entry_score}/100, +{t.pnl_pct:.1f}%, Age {t.duration_str}" for t in wins]) or "Tidak ada"}

LOSSES ({len(losses)}):
{chr(10).join([f"- {t.token_symbol}: Score {t.entry_score}/100, {t.pnl_pct:.1f}%, Age {t.duration_str}" for t in losses]) or "Tidak ada"}

Tulis markdown ringkas berisi:
1. Win Rate batch ini
2. BULLISH PATTERNS ditemukan
3. BEARISH/AVOID PATTERNS ditemukan
4. Rekomendasi spesifik untuk batch berikutnya

Max 200 kata, format markdown.
"""
        return await self._call_api(session, prompt, max_tokens=400)

    def _fallback_improve(self, current: FilterConfig) -> tuple:
        f = copy.copy(current)
        f.min_liquidity_usd  = min(f.min_liquidity_usd * 1.3, 200_000)
        f.min_volume_24h_usd = min(f.min_volume_24h_usd * 1.3, 500_000)
        f.min_buy_sell_ratio = min(f.min_buy_sell_ratio + 0.2, 3.0)
        f.min_age_minutes    = min(f.min_age_minutes + 5, 30)
        f.generation        += 1
        return f, "Fallback: naikkan liquidity & volume 30%, perketat buy/sell ratio +0.2, naikkan min age +5m"


# ──────────────────────────────────────────────────────────────────
# TELEGRAM NOTIFIER
# ──────────────────────────────────────────────────────────────────

class TelegramBot:
    BASE = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}"

    async def send(self, session: aiohttp.ClientSession, text: str, parse_mode: str = "HTML"):
        try:
            payload = {
                "chat_id": TELEGRAM_CHAT_ID,
                "text": text,
                "parse_mode": parse_mode,
                "disable_web_page_preview": True,
            }
            async with session.post(
                f"{self.BASE}/sendMessage",
                json=payload,
                timeout=aiohttp.ClientTimeout(total=10)
            ) as r:
                result = await r.json()
                if not result.get("ok"):
                    logging.warning(f"Telegram error: {result}")
        except Exception as e:
            logging.error(f"Telegram send error: {e}")

    def format_startup(self, paper: bool) -> str:
        mode = "📄 PAPER TRADING" if paper else "💰 LIVE TRADING"
        return f"""
🤖 <b>NDA4 AI TRADING BOT v2.0 STARTED</b>
{mode}

💼 Balance: {INITIAL_BALANCE_SOL} SOL
📦 Trade Size: {TRADE_SIZE_SOL} SOL per trade
🎯 Min Entry Score: {MIN_ENTRY_SCORE}/100
🎯 Target Win Rate: {TARGET_WIN_RATE*100:.0f}%
⚡ Max Open Trades: {MAX_OPEN_TRADES}
🔍 Scan Interval: {SCAN_INTERVAL_SEC}s
📊 Report Interval: 1 jam
🔧 Filter Gen: #1
🤖 AI Model: {OPENROUTER_MODEL}

Scanners: DexScreener + GMGN
Bot aktif scan token Solana secara real-time... 📡
""".strip()

    def format_trade_open(self, trade: Trade) -> str:
        icon   = "🟡" if trade.entry_type == "limit" else "🟢"
        status = "LIMIT ORDER" if trade.entry_type == "limit" else "MARKET ENTRY"
        paper  = "📄 PAPER" if trade.is_paper else "💰 LIVE"
        return f"""
{icon} <b>NEW TRADE — {status}</b> {paper}

🪙 Token: <b>${trade.token_symbol}</b>
📊 Entry Type: <b>{trade.entry_type.upper()}</b>
🏆 Score: <b>{trade.entry_score}/100</b>
💰 Entry Price: <b>${trade.entry_price:.8f}</b>
🎯 Take Profit: <b>${trade.tp_price:.8f}</b> (+{(trade.tp_price/trade.entry_price-1)*100:.1f}%)
🛑 Stop Loss: <b>${trade.sl_price:.8f}</b> (-{(1-trade.sl_price/trade.entry_price)*100:.1f}%)
💼 Size: <b>{trade.size_sol} SOL</b>
🔗 <a href="https://dexscreener.com/solana/{trade.token_address}">DexScreener</a> | <a href="https://birdeye.so/token/{trade.token_address}">Birdeye</a>

📝 AI Reason: <i>{trade.ai_reasoning}</i>
🕐 {datetime.now().strftime('%H:%M:%S')}
""".strip()

    def format_trade_close(self, trade: Trade) -> str:
        won  = trade.pnl_sol and trade.pnl_sol > 0
        icon = "✅" if won else "❌"
        paper = "📄 PAPER" if trade.is_paper else "💰 LIVE"
        return f"""
{icon} <b>TRADE CLOSED — {'PROFIT' if won else 'LOSS'}</b> {paper}

🪙 Token: <b>${trade.token_symbol}</b>
📊 Exit Reason: <b>{trade.status.replace('_', ' ').upper()}</b>
🏆 Entry Score: <b>{trade.entry_score}/100</b>
💰 Entry: <b>${trade.entry_price:.8f}</b>
💱 Exit: <b>${trade.exit_price:.8f}</b>
{'📈' if won else '📉'} PnL: <b>{trade.pnl_sol:+.4f} SOL ({trade.pnl_pct:+.1f}%)</b>
⏱ Duration: {trade.duration_str}
🕐 {datetime.now().strftime('%H:%M:%S')}
""".strip()

    def format_filter_improve(self, old_gen: int, new_gen: int, notes: str) -> str:
        return f"""
🔧 <b>AI FILTER IMPROVED</b>

Generation: {old_gen} → {new_gen}
Trigger: 3x loss berturut-turut

📋 Perubahan:
<i>{notes}</i>

Bot akan lebih selektif dalam memilih entry. 💪
""".strip()

    def format_risk_alert(self, reason: str) -> str:
        return f"""
⚠️ <b>RISK MANAGEMENT ALERT</b>

🚨 {reason}

Bot berhenti trading sementara untuk proteksi kapital.
Review manual diperlukan.
""".strip()

    def format_hourly_report(self, state: BotState) -> str:
        open_trades   = state.open_trades
        pending       = [t for t in open_trades if t.status == "pending_limit"]
        running       = [t for t in open_trades if t.status == "open"]
        uptime        = timedelta(seconds=int(time.time() - state.started_at))
        mode_label    = "📄 PAPER" if PAPER_TRADE else "💰 LIVE"
        pnl_emoji     = "📈" if state.total_pnl_sol >= 0 else "📉"

        lines = [
            f"📊 <b>LAPORAN JAM — {datetime.now().strftime('%H:%M')} | {mode_label}</b>",
            f"━━━━━━━━━━━━━━━━━━━━",
            f"⏱ Uptime: {str(uptime).split('.')[0]}",
            f"💼 Balance: <b>{state.balance_sol:.4f} SOL</b>",
            f"{pnl_emoji} Total PnL: <b>{state.total_pnl_sol:+.4f} SOL</b>",
            f"📊 Portfolio: <b>{state.portfolio_change_pct*100:+.1f}%</b>",
            f"",
            f"📉 <b>STATISTIK TRADE</b>",
            f"Total Trade: {state.total_trades}",
            f"✅ Win: {state.winning_trades} | ❌ Loss: {state.losing_trades}",
            f"🎯 Win Rate: <b>{state.win_rate*100:.1f}%</b> (Target: {TARGET_WIN_RATE*100:.0f}%)",
            f"🔁 Filter Gen: #{state.filters.generation} | Improve: {state.improve_count}x",
            f"",
        ]

        if running:
            lines.append(f"🟢 <b>POSISI TERBUKA ({len(running)})</b>")
            for t in running:
                if t.current_price and t.entry_price:
                    pct     = (t.current_price - t.entry_price) / t.entry_price * 100
                    pnl_sol = (t.current_price - t.entry_price) / t.entry_price * t.size_sol
                    lines.append(
                        f"• ${t.token_symbol} [{t.entry_score}/100] | "
                        f"Entry ${t.entry_price:.6f} | Now ${t.current_price:.6f} | "
                        f"{'📈' if pct >= 0 else '📉'} {pct:+.1f}% ({pnl_sol:+.4f} SOL)"
                    )
                    lines.append(f"  🎯 TP: ${t.tp_price:.6f} | 🛑 SL: ${t.sl_price:.6f}")
            lines.append("")

        if pending:
            lines.append(f"🟡 <b>LIMIT ORDER ({len(pending)})</b>")
            for t in pending:
                lines.append(
                    f"• ${t.token_symbol} | Limit: ${t.entry_price:.6f} | "
                    f"TP: ${t.tp_price:.6f} | SL: ${t.sl_price:.6f}"
                )
            lines.append("")

        recent_closed = [t for t in state.finished_trades[-5:] if t.status in ("tp_hit", "sl_hit")]
        if recent_closed:
            lines.append(f"📋 <b>TRADE TERAKHIR</b>")
            for t in recent_closed:
                icon = "✅" if t.status == "tp_hit" else "❌"
                lines.append(f"{icon} ${t.token_symbol} [{t.entry_score}/100] | {t.pnl_sol:+.4f} SOL ({t.pnl_pct:+.1f}%)")
            lines.append("")

        lines.append(f"🔍 Scan: {state.scanned_tokens_today} | Skip: {state.skipped_tokens_today}")
        lines.append(f"⚙️ Gen #{state.filters.generation} | Min Score: {MIN_ENTRY_SCORE}")
        lines.append(f"🤖 Model: {OPENROUTER_MODEL}")

        return "\n".join(lines)


# ──────────────────────────────────────────────────────────────────
# JOURNAL MANAGER
# ──────────────────────────────────────────────────────────────────

class JournalManager:
    def __init__(self):
        self._trade_batch = []

    def log_trade_open(self, trade: Trade, token: TokenData):
        entry = f"""
## Trade #{trade.id} — {datetime.now().strftime('%Y-%m-%d %H:%M')}

**Token**: {token.name} ({trade.token_symbol}) — `{trade.token_address}`
**Scanner**: DexScreener
**Entry Price**: ${trade.entry_price:.8f}
**Position Size**: {trade.size_sol} SOL ({"Paper" if trade.is_paper else "Live"})
**Entry Score**: {trade.entry_score}/100
**Entry Type**: {trade.entry_type.upper()}
**TP**: ${trade.tp_price:.8f} | **SL**: ${trade.sl_price:.8f}

### Entry Reasoning
- {trade.ai_reasoning}
- Liquidity: ${token.liquidity_usd:,.0f} | Volume 24h: ${token.volume_24h:,.0f}
- Buy/Sell 5m: {token.buy_count_5m}/{token.sell_count_5m} | Price change 5m: {token.price_change_5m:+.1f}%
- Age: {token.age_minutes:.0f} menit | Holders: {token.holder_count}
"""
        append_to_journal(entry)

    def log_trade_close(self, trade: Trade):
        won  = trade.pnl_sol and trade.pnl_sol > 0
        icon = "✅ WIN" if won else "❌ LOSS"
        outcome = f"""
### Outcome — {icon}
- **Exit Price**: ${trade.exit_price:.8f}
- **Exit Reason**: {trade.status.replace('_', ' ').upper()}
- **PnL**: {trade.pnl_sol:+.4f} SOL ({trade.pnl_pct:+.1f}%)
- **Duration**: {trade.duration_str}

### Learnings
- _[Bot akan update otomatis saat 10 trade selesai]_

---
"""
        append_to_journal(outcome)
        self._trade_batch.append(trade)

    def should_update_strategy(self) -> bool:
        return len(self._trade_batch) >= 10

    def flush_batch(self) -> list:
        batch = self._trade_batch[:]
        self._trade_batch.clear()
        return batch

    def log_strategy_iteration(self, state: BotState, notes: str):
        finished = state.finished_trades
        wins     = sum(1 for t in finished if t.pnl_sol and t.pnl_sol > 0)
        losses   = sum(1 for t in finished if t.pnl_sol and t.pnl_sol <= 0)
        wr       = wins / (wins + losses) * 100 if (wins + losses) > 0 else 0
        avg_win  = sum(t.pnl_pct for t in finished if t.pnl_pct and t.pnl_pct > 0) / max(wins, 1)
        avg_loss = sum(t.pnl_pct for t in finished if t.pnl_pct and t.pnl_pct <= 0) / max(losses, 1)

        entry = f"""
## Strategy Iteration #{state.improve_count} — {datetime.now().strftime('%Y-%m-%d %H:%M')}
Filter Generation: #{state.filters.generation}

### Performance
- Win Rate: {wr:.1f}%
- Avg Win: +{avg_win:.1f}% | Avg Loss: {avg_loss:.1f}%
- Net PnL: {state.total_pnl_sol:+.4f} SOL

### AI Pattern Notes
{notes}

---
"""
        append_to_strategy(entry)


# ──────────────────────────────────────────────────────────────────
# TRADING ENGINE — Main orchestrator
# ──────────────────────────────────────────────────────────────────

class TradingEngine:
    def __init__(self):
        self.scanner = SolanaScanner()
        self.ai      = AIAgent()
        self.filter  = FilterEngine()
        self.tg      = TelegramBot()
        self.journal = JournalManager()
        self.state   = BotState()

    async def run(self):
        init_reference_files()
        logging.info("🚀 NDA4 Bot v2 started!")
        async with aiohttp.ClientSession() as session:
            await self.tg.send(session, self.tg.format_startup(PAPER_TRADE))
            await asyncio.gather(
                self._scan_loop(session),
                self._price_update_loop(session),
                self._report_loop(session),
            )

    # ── Scan loop ──────────────────────────────────────────────────

    async def _scan_loop(self, session: aiohttp.ClientSession):
        while True:
            try:
                await self._do_scan(session)
            except Exception as e:
                logging.error(f"Scan loop error: {e}")
            await asyncio.sleep(SCAN_INTERVAL_SEC)

    async def _do_scan(self, session: aiohttp.ClientSession):
        if not self.state.can_open_trade():
            reason = (
                "paused (too many consecutive losses)" if self.state.paused_due_to_losses
                else "daily loss limit hit" if self.state.daily_loss_triggered
                else f"max trades open ({len(self.state.open_trades)}/{MAX_OPEN_TRADES})"
                if len(self.state.open_trades) >= MAX_OPEN_TRADES
                else f"insufficient balance ({self.state.balance_sol:.3f} SOL)"
            )
            logging.info(f"Skip scan: {reason}")
            return

        trending   = await self.scanner.get_trending_tokens(session)
        new_tokens = await self.scanner.get_new_tokens(session)
        all_tokens = list({t.address: t for t in (trending + new_tokens) if t.address}.values())
        self.state.scanned_tokens_today += len(all_tokens)

        open_addresses = {t.token_address for t in self.state.open_trades}
        candidates = []

        for token in all_tokens:
            if token.address in open_addresses:
                continue
            score = token.entry_score()
            if score < MIN_ENTRY_SCORE:
                self.state.skipped_tokens_today += 1
                logging.debug(f"SKIP {token.symbol}: score {score} < {MIN_ENTRY_SCORE}")
                continue
            passed, reason = self.filter.passes(token, self.state.filters)
            if not passed:
                self.state.skipped_tokens_today += 1
                logging.debug(f"SKIP {token.symbol}: {reason}")
                continue
            candidates.append(token)

        if not candidates:
            logging.info("No candidates passed filters this scan")
            return

        # Sort by entry score (desc), then by price_change_5m
        candidates.sort(key=lambda t: (t.entry_score(), t.price_change_5m), reverse=True)
        logging.info(f"Candidates: {len(candidates)} | Top: {candidates[0].symbol} (score={candidates[0].entry_score()})")

        for token in candidates[:3]:
            if not self.state.can_open_trade():
                break
            decision = await self.ai.analyze_token(session, token, self.state)
            if not decision:
                continue
            if decision.get("action") == "BUY" and decision.get("confidence", 0) >= 60:
                await self._open_trade(session, token, decision)
                await asyncio.sleep(2)

    async def _open_trade(self, session: aiohttp.ClientSession, token: TokenData, decision: dict):
        entry_type  = decision.get("entry_type", "market")
        entry_price = float(decision.get("entry_price_usd", token.price_usd))
        tp_price    = float(decision.get("tp_price_usd", entry_price * self.state.filters.tp_multiplier))
        sl_price    = float(decision.get("sl_price_usd", entry_price * self.state.filters.sl_multiplier))
        reasoning   = decision.get("reasoning", "")

        # Validasi TP/SL
        tp_price = max(tp_price, entry_price * 1.10)          # min TP +10%
        sl_price = min(sl_price, entry_price * (1 - STOP_LOSS_PCT))  # max SL -30%
        sol_usd  = token.price_usd / token.price_sol if token.price_sol > 0 else 150

        trade = Trade(
            id=self.state.new_trade_id(),
            token_address=token.address,
            token_symbol=token.symbol,
            entry_type=entry_type,
            entry_price=entry_price,
            entry_price_sol=entry_price / sol_usd,
            tp_price=tp_price,
            sl_price=sl_price,
            size_sol=TRADE_SIZE_SOL,
            status="pending_limit" if entry_type == "limit" else "open",
            opened_at=time.time(),
            current_price=token.price_usd,
            ai_reasoning=reasoning,
            entry_score=token.entry_score(),
            is_paper=PAPER_TRADE,
        )

        self.state.trades.append(trade)
        self.state.balance_sol -= TRADE_SIZE_SOL
        self.state.total_trades += 1

        logging.info(
            f"OPEN {trade.id} ${token.symbol} {entry_type} @ ${entry_price:.8f} "
            f"| Score: {trade.entry_score}/100"
        )
        self.journal.log_trade_open(trade, token)
        await self.tg.send(session, self.tg.format_trade_open(trade))

    # ── Price update & TP/SL check ─────────────────────────────────

    async def _price_update_loop(self, session: aiohttp.ClientSession):
        while True:
            try:
                await self._update_prices(session)
            except Exception as e:
                logging.error(f"Price update error: {e}")
            await asyncio.sleep(15)

    async def _update_prices(self, session: aiohttp.ClientSession):
        for trade in list(self.state.open_trades):
            token_data = await self.scanner.get_token_detail(session, trade.token_address)
            if not token_data:
                continue

            current_price    = token_data.price_usd
            trade.current_price = current_price
            trade.last_updated  = time.time()

            # Aktifkan limit order
            if trade.status == "pending_limit":
                if current_price <= trade.entry_price:
                    trade.status = "open"
                    logging.info(f"Limit filled: {trade.id} @ ${current_price:.8f}")
                    await self.tg.send(session,
                        f"🟢 <b>LIMIT ORDER FILLED</b>\n"
                        f"${trade.token_symbol} @ ${trade.entry_price:.8f}\n"
                        f"TP: ${trade.tp_price:.8f} | SL: ${trade.sl_price:.8f}"
                    )
                continue

            # Check TP/SL
            if current_price >= trade.tp_price:
                await self._close_trade(session, trade, current_price, "tp_hit")
            elif current_price <= trade.sl_price:
                await self._close_trade(session, trade, current_price, "sl_hit")

    async def _close_trade(
        self, session: aiohttp.ClientSession, trade: Trade, exit_price: float, reason: str
    ):
        trade.exit_price = exit_price
        trade.closed_at  = time.time()
        trade.status     = reason

        pct = (exit_price - trade.entry_price) / trade.entry_price
        trade.pnl_pct = pct * 100
        trade.pnl_sol = pct * trade.size_sol

        self.state.total_pnl_sol += trade.pnl_sol
        self.state.balance_sol   += TRADE_SIZE_SOL + trade.pnl_sol

        won = reason == "tp_hit"
        if won:
            self.state.winning_trades    += 1
            self.state.consecutive_losses = 0
            self.state.paused_due_to_losses = False
        else:
            self.state.losing_trades      += 1
            self.state.consecutive_losses += 1
            self.state.recent_losses.append(trade)

        logging.info(
            f"CLOSE {trade.id} ${trade.token_symbol} {reason} "
            f"@ ${exit_price:.8f} | PnL: {trade.pnl_sol:+.4f} SOL ({trade.pnl_pct:+.1f}%)"
        )

        self.journal.log_trade_close(trade)
        await self.tg.send(session, self.tg.format_trade_close(trade))

        # Risk management checks
        await self._check_risk_rules(session)

        # Auto-improve filters setelah 3x loss
        if self.state.consecutive_losses >= CONSECUTIVE_LOSS_TRIGGER:
            await self._improve_filters(session)

        # Update strategy setiap 10 trade
        if self.journal.should_update_strategy():
            await self._update_strategy(session)

    # ── Risk management ─────────────────────────────────────────────

    async def _check_risk_rules(self, session: aiohttp.ClientSession):
        # Rule 1: Daily loss limit
        if self.state.check_daily_loss_limit():
            msg = f"Daily loss limit {MAX_DAILY_LOSS_PCT*100:.0f}% terpicu. Portfolio: {self.state.portfolio_change_pct*100:.1f}%"
            logging.warning(f"⚠️ {msg}")
            await self.tg.send(session, self.tg.format_risk_alert(msg))

        # Rule 2: Consecutive losses pause
        if self.state.consecutive_losses >= MAX_CONSECUTIVE_LOSSES:
            self.state.paused_due_to_losses = True
            msg = f"{MAX_CONSECUTIVE_LOSSES}x consecutive losses. Bot di-pause untuk review."
            logging.warning(f"⚠️ {msg}")
            await self.tg.send(session, self.tg.format_risk_alert(msg))

    # ── Filter improvement ──────────────────────────────────────────

    async def _improve_filters(self, session: aiohttp.ClientSession):
        old_gen = self.state.filters.generation
        logging.info(f"🔧 Improving filters (gen {old_gen})...")
        new_filters, notes = await self.ai.improve_filters(session, self.state)
        self.state.filters             = new_filters
        self.state.consecutive_losses  = 0
        self.state.improve_count      += 1

        logging.info(f"✅ Filter improved: gen {old_gen} → {new_filters.generation}")
        await self.tg.send(session, self.tg.format_filter_improve(old_gen, new_filters.generation, notes))

    # ── Strategy pattern update ─────────────────────────────────────

    async def _update_strategy(self, session: aiohttp.ClientSession):
        batch = self.journal.flush_batch()
        logging.info(f"📚 Updating strategy with {len(batch)} trade batch...")
        pattern_notes = await self.ai.generate_pattern_update(session, self.state)
        if pattern_notes:
            self.journal.log_strategy_iteration(self.state, pattern_notes)
            await self.tg.send(session,
                f"📚 <b>STRATEGY UPDATE</b>\n\n"
                f"Batch {self.state.total_trades} trade dianalisis.\n\n"
                f"<i>{pattern_notes[:400]}...</i>"
            )

    # ── Hourly report ───────────────────────────────────────────────

    async def _report_loop(self, session: aiohttp.ClientSession):
        await asyncio.sleep(REPORT_INTERVAL_SEC)
        while True:
            try:
                report = self.tg.format_hourly_report(self.state)
                await self.tg.send(session, report)
                self.state.last_report_at = time.time()
                logging.info("📊 Hourly report sent")
            except Exception as e:
                logging.error(f"Report error: {e}")
            await asyncio.sleep(REPORT_INTERVAL_SEC)


# ──────────────────────────────────────────────────────────────────
# ENTRY POINT
# ──────────────────────────────────────────────────────────────────

async def main():
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        handlers=[
            logging.StreamHandler(),
            logging.FileHandler("bot.log", encoding="utf-8"),
        ],
    )

    missing = []
    if TELEGRAM_BOT_TOKEN  == "YOUR_BOT_TOKEN":      missing.append("TELEGRAM_BOT_TOKEN")
    if TELEGRAM_CHAT_ID    == "YOUR_CHAT_ID":        missing.append("TELEGRAM_CHAT_ID")
    if OPENROUTER_API_KEY  == "YOUR_OPENROUTER_KEY": missing.append("OPENROUTER_API_KEY")

    if missing:
        print(f"\n❌ Set environment variables dulu: {', '.join(missing)}")
        print("   Contoh: export TELEGRAM_BOT_TOKEN=xxx")
        print("   Atau buat file .env dan load dengan python-dotenv\n")
        return

    mode = "📄 PAPER TRADING (simulasi)" if PAPER_TRADE else "💰 LIVE TRADING (real money!)"
    print(f"\n{'='*60}")
    print(f"  NDA4 AI TRADING BOT v2.0")
    print(f"  Mode: {mode}")
    print(f"  Balance: {INITIAL_BALANCE_SOL} SOL | Trade size: {TRADE_SIZE_SOL} SOL")
    print(f"  Min Entry Score: {MIN_ENTRY_SCORE}/100 | AI: {OPENROUTER_MODEL}")
    print(f"{'='*60}\n")

    engine = TradingEngine()
    await engine.run()


if __name__ == "__main__":
    asyncio.run(main())
